### ISSUE TITLE
How to use mssh behind a proxy?

### ISSUE THREAD

**Issue by left4taco** [aws/aws-ec2-instance-connect-cli#15]
I need to connect to an AWS instance, but the Internet speed is very slow from my service provide. However, I can find a proxy which is fast from both my home and the AWS instance. Is there anyway to connect through the socks5 proxy?

Thanks

**Comment by CptTZ** [comment]
`mssh` will parse and then pass switches to underlying **ssh client**, so invoking `mssh ec2-user@i-1234567890abcd -v` will cause ssh client to print debugging messages.

That said, you could utilize standard ssh switches (e.g. `-o ProxyCommand='xxx'`) to let `mssh` instruct ssh client connecting using SOCKS 5 proxies.

**Comment by CptTZ** [comment]
Closing as no response
