### ISSUE TITLE
AWS SSO Support does not work

### ISSUE THREAD

**Issue by z0mbix** [aws/aws-ec2-instance-connect-cli#17]
I currently have SSO credentials using the command `aws sso login`, which work fine for aws cli (v2) commands, but `mssh` does not support using these credentials:

```
mssh i-02d6e842cb8375f64
Unable to locate credentials
```

```
mssh --profile nonprod i-02d6e842cb8375f64
Unable to locate credentials
```

```
aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/19.3.0 botocore/2.0.0dev4
```

**Comment by CptTZ** [comment]
Thanks for reporting! We do not support parsing SSO credentials at this time, I have created a feature request for this.

**Comment by bigwheel** [comment]
FYI: Im using [linaro\-its/aws2\-wrap](https://github.com/linaro-its/aws2-wrap) as workaround.

**Comment by urz9999** [comment]
Hi guys, maybe give a try to our project: [Leapp](https://github.com/Noovolari/leapp), we recently added support for AWS SSO to help with incompatibilities with third party tools where you need to have credentials in standard .aws/credentials location to make them work. We manage AWS SSO login and retrieval of all the accounts/roles couple for you then we create short-lived temporary credentials in .aws/credentials file.

**Comment by z0mbix** [comment]
I ended up creating https://github.com/z0mbix/essh instead of using mssh. It supports AWS SSO from `v0.0.5` onwards.

**Comment by derektamsen** [comment]
AWS SSO credentials with a recent `pip install ec2instanceconnectcli` appears to be working.

```
Name: ec2instanceconnectcli
Version: 1.0.2
Summary: Command Line Interface for AWS EC2 Instance Connect
Home-page: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/user/.local/lib/python3.9/site-packages
Requires: cryptography, botocore
Required-by: 
```

Reviewing the code it calls [`botocore.session.get_session()`](https://github.com/aws/aws-ec2-instance-connect-cli/blob/470ed6758fae737c28385947b005ecdf4092b08c/ec2instanceconnectcli/EC2InstanceConnectCLI.py#L137) which means support for aws sso is based on whether the dependency botocore supports sso profiles. As of botocore [1.14.0](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#1140), aws sso profiles are support. I was able to successful use `mssh` to connect using aws sso with botocore 1.23.2.

## Steps

1. `pip install ec2instanceconnectcli`
2. `aws sso login --profile <your_sso_profile_config_name>`
3. `mssh --profile <your_sso_profile_config_name> --region <instance_region> <user>@<instance_id>`

**Comment by komapa** [comment]
> Thanks for reporting! We do not support parsing SSO credentials at this time, I have created a feature request for this.

What kind of joke is this? Official tool does not even follow the breaking changes from other teams.
