### ISSUE TITLE
Reject unknown flags or provide meaningful feedback?

### ISSUE THREAD

**Issue by jfreeland** [aws/aws-ec2-instance-connect-cli#18]
I was attempting to use mssh earlier to connect to a machine and thinking I was using the correct command.

```
jfreeland@foo : ~ > mssh -r us-west-2 -i i-00000
Warning: Identity file ec2-user@w.x.y.z not accessible: No such file or directory.
```

It took me a couple minutes to realize I didn't need to pass a `-i` flag, and I was able to connect fine after removing it, but it seems like mssh should have barked about this.

**Comment by CptTZ** [comment]
Thank you for bringing this up! We are continuously working on improving customer experience and I will definitely note this issue in our backlog.
