### ISSUE TITLE
Connection fails on Windows: "command-line: line 0: Bad configuration option: 'identitiesonly"

### ISSUE THREAD

**Issue by craigholm** [aws/aws-ec2-instance-connect-cli#21]
Beginning with 1.0.1, attempting to connect to an instance on Windows 10 (1909, with the built-in ssh client and default cmd.exe command shell) fails with the following error message:

```
command-line: line 0: Bad configuration option: 'identitiesonly
```

I'm guessing it's because the IdentitiesOnly=yes argument is single-quoted.  Rolling back to 1.0.0 fixes the problem.

**Comment by ohitspaul** [comment]
Thank you for reporting the issue @craigholm. This should be addressed with release 1.0.2: https://github.com/aws/aws-ec2-instance-connect-cli/releases/tag/1.0.2

Commit here: https://github.com/aws/aws-ec2-instance-connect-cli/commit/a32bde5e49f3d2aa80007558f254522d6e7e7380

Closing for now, please let us know if the issue persists with the latest release.
