### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by echoboomer** [aws/aws-ec2-instance-connect-cli#7]
Are there any plans to add support for logging sessions? We recently migrated from using `ssm` to using `ec2-instance-connect`, but we did sacrifice the ability to log sessions.

**Comment by LordAlfredo** [comment]
Do you mean within the CLI or on the instance side?  As the CLI currently hooks into the native ssh executable the former is not planned.  As for the latter there are several ways to configure server-side ssh session logging, it is out of scope for this CLI as it is meant just as a wrapper for connecting to an instance via EC2 Instance Connect.

**Comment by echoboomer** [comment]
My mistake - I probably asked about this in the wrong place. Thanks the clarification!
